name: astro_app_assesment
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - lib/assests/background.png
    - lib/assests/firstpage.jpg
    - lib/assests/yogi2.jpg
    - lib/assests/yogi1.jpg
    - lib/assests/yogi3.jpg
  
  
